### ISSUE TITLE
No check for player entering drivers seat

### ISSUE THREAD

**Issue by WayfaringCookie** [JaredScar/DiscordVehicleRestrictions#1]
The script works flawlessly if spawning the vehicle in. The issue I am having is if someone jumps into the drivers seat of a restricted car it allows them to use it.

**Comment by JaredScar** [comment]
You sure?

```lua
if IsPedInAnyVehicle(ped, false) then
			veh = GetVehiclePedIsUsing(ped)
		else
			veh = GetVehiclePedIsTryingToEnter(ped)
        end
```

**Comment by WayfaringCookie** [comment]
This may have been in relation to the other issue you fixed a few minutes ago. Ill carry out some testing now and let you know if it is resolved.
