### ISSUE TITLE
Checks fail after permission granted

### ISSUE THREAD

**Issue by WayfaringCookie** [JaredScar/DiscordVehicleRestrictions#2]
The script restricts as it is meant to until the user enters a vehicle they are allowed to drive. Once they spawn into a vehicle they are allowed to drive it allows them to spawn any restricted model too.

For example: User tries to spawn into Rhino - Permission denied, Spawns into a BMW M5 - Permission granted. Spawns back into a Rhino tank - Permission granted.

Restarting the resource resolves until the user repeats the above steps again.

Hope this helps.

**Comment by JaredScar** [comment]
Will look into this.

**Comment by JaredScar** [comment]
Should be fixed now, https://github.com/JaredScar/DiscordVehicleRestrictions/commit/d62d145e367d9a311100e8dfb22e3f3ce8643c33
