### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [JaredScar/DiscordVehicleRestrictions#3]
Is there a way to have it kick someone out of the car instead of delete it? (In this case, mechanic RP, they get in a car to fix it but don't actually have the right permissions to be able to drive it themselves so it DV's in the middle of an RP haha)

**Comment by JaredScar** [comment]
You can change the code quite easily to do this instead. A simple post on CFX forums should do you valid justification hopefully.
