### ISSUE TITLE
Getting this Error when I pull out a vehicle that is supposed to be restricted.

### ISSUE THREAD

**Issue by OfficerMills** [JaredScar/DiscordVehicleRestrictions#6]
I setup Badger API as well as Discord Vehicle Restrictions but when I attempt to remove a vehicle that's supposed to be restricted I get the error you see in this attachment. Not sure how to fix.
![DiscordVehicleRestrictionsERROR](https://github.com/JaredScar/DiscordVehicleRestrictions/assets/149747958/fa44c6e1-f9ad-467a-8d83-2f34d7eeca68)
![DiscordVehicleRestrictionclientLUAline44](https://github.com/JaredScar/DiscordVehicleRestrictions/assets/149747958/0495353b-2a66-46b1-881e-06117c5970d7)

**Comment by JaredScar** [comment]
User error
